# Generated by Django 3.2.3 on 2021-05-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_auto_20210530_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='workingdays',
            name='standard',
        ),
        migrations.DeleteModel(
            name='SlotSubject',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
